### ISSUE TITLE
gnd and 5v swapped on oled?

### ISSUE THREAD

**Issue by Commodore-Bench** [tebl/C64-Pi1541-Module#2]
Ordered the latest version of this (late spring 2020) from pcbway.  What I built doesn't work.  one of the issues I think I have identified is that the 5v and ground for the oled are swapped if you use header pins.  I am going to work around this by using wires.

**Comment by Commodore-Bench** [comment]
Just a quick follow up.  I obviously meant 3.3v for the oled. Once I wired that up correctly I was able to get the PI1541 working. I had a bad 7406 that was causing other issues not related to the board layout.

**Comment by tebl** [comment]
Sorry about the late follow up, I've got a bit too many projects that I seem to do and forget about, glad to see that you got it working. Regarding the OLED, various later clones have reshuffled the pins somewhat so these days it's a bit random which kind you end up getting. I've incorporated this into the later C64 Pi1541-II project.
